### PR TITLE
Add `t2_seg-manual_labeled.nii.gz` (output of `sct_label_vertebrae`)

### PR DESCRIPTION
**Pull request by sandrinebedard**
## Description
THis PR add labled segmentation used in unit testing for `sct_process_segmentation` using `-normalize PAM50` (see [PR](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3977))

### CODE REVIEW

**Review by joshuacwnewton — COMMENTED** [review]
One thing that we can do for now is manually add the new file to the a new `.zip` archive, then add the `.zip` as a second asset on the existing release:

image

That way, we can still test the PR would necessarily merging the new file just yet, which addresses https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3977#issuecomment-1402425929.

(The only reason I haven't approved yet is because I'm nervous about prematurely committing binary file changes to a repo without having fully tested things on the SCT side first. See: My previous mistake in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2179#issuecomment-1400571127.)

**Comment by joshuacwnewton** [comment]
I've added a new manually-created archive, [`sct_testing_data-PR3977.zip`](https://github.com/spinalcordtoolbox/sct_testing_data/releases/download/r20210330230310/sct_testing_data-PR3977.zip), to the [`r20210330230310`](https://github.com/spinalcordtoolbox/sct_testing_data/releases/r20210330230310/) release.

This link can be temporarily used in #3977 while we test the PR. When #3977 is ready to merge, then we can merge _this_ PR, create a new `sct_testing_data` release, and update the link in #3977 once more.

**Review by joshuacwnewton — APPROVED** [review]
This LGTM, but I also think it might be good to document how this file was generated?

(I'd say put it in the `README.md`, but the readme isn't very useful right now... so maybe just commenting in this PR is okay.)

Did you label it manually? (Since `sct_label_vertebrae` fails for `sct_testing_data` due to missing c2/c3 disc...)

**Comment by sandrinebedard** [comment]
The file was generated with following steps:
1. Manual labeling of the posterior tip of the disc:
~~~
sct_label_utils -i t2.nii.gz -create-viewer 1:20
~~~
image
[t2_disc-manual.nii.gz](https://github.com/spinalcordtoolbox/sct_testing_data/files/10679408/t2_disc-manual.nii.gz)


2. Compute labeled segmentation:
~~~
sct_label_vertebrae -i t2.nii.gz -s t2_seg-manual.nii.gz -c t2 -discfile t2_disc-manual.nii.gz
~~~
Giving the output: `t2_seg-manual_labeled.nii.gz`

**Pull request merged**
